### PR TITLE
Typo and grammar fixes for README.me

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by justinclift** [comment]
I'm unsure about the last bit regarding Travis CI. Did I understand the meaning in the original paragraph well enough to reword it?

**Comment by cschwede** [comment]
Thanks Justin for the fixes!

I submitted the patch for review on SF itself: http://softwarefactory.enovance.com/r/714

This should be merged within a few hours.

**Comment by cschwede** [comment]
Merged via softwarefactory.enovance.com

**Comment by justinclift** [comment]
Heh Heh Heh I didn't think that through did I? :wink:

**Pull request closed without merging**
